`define MODULE_NAME FFT_Top
`define TARGET_DEVICE_GW5A_25A
`define FIXED
`define FFT4096
`define POINTS 4096
`define POINTS_LOG 12
`define HIGH_PERFORMANCE
`define MODE_FORWARD
`define OUTPUT_NATURAL
`define SCALING_RS111
`define INPUT_DATA_WIDTH 8
`define INPUT_DATA_WIDTH_LOG 3
`define TWIDDLE_FACTOR_WIDTH 8
`define TWIDDLE_FACTOR_WIDTH_LOG 3
`define OUTPUT_DATA_WIDTH 8
`define OUTPUT_DATA_WIDTH_LOG 3
`define REDUCTION_TRUNCATION
`define LUT_BASED
`define DISTRIBUTED_MEMORY
`define TDF_DISTRIBUTED_MEMORY
